---
apiVersion: v1
kind: Secret
metadata:
  name: csi-rbd-secret
  namespace: ceph-csi-rbd
stringData:
  # Required for statically provisioned volumes
  userID: admin 
  userKey: XXX #ceph用户key

  # Required for dynamically provisioned volumes
  adminID: admin 
  adminKey:  XXX #ceph用户key
